name: Continuous Integration

on:
  pull_request:
    branches: ['4.x', '3.x']
  push:
    branches: ['4.x', '3.x']

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }} - Symfony ${{ matrix.symfony-version }})
    runs-on: ubuntu-20.04
    env:
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

    strategy:
      matrix:
        php-version:
          - '7.4'
          - '8.0'
          - '8.1'
        symfony-version:
          - '4.4.*'
          - '5.3.*'
          - '5.4.x@dev'
        include:
          - php-version: '8.0'
            symfony-version: '6.0.x@dev'
            env:
              SYMFONY_DEPRECATIONS_HELPER: disabled
          - php-version: '8.1'
            symfony-version: '6.0.x@dev'
            env:
              SYMFONY_DEPRECATIONS_HELPER: disabled

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install PHP with pcov
        uses: shivammathur/setup-php@v2
        with:
          coverage: pcov
          php-version: ${{ matrix.php-version }}
          extensions: pdo_sqlite

      - name: Install Symfony Flex
        run: composer global require --no-progress --no-scripts --no-plugins symfony/flex

      - name: Set composer minimum stability
        run: composer config minimum-stability dev
        if: matrix.symfony-version == '5.4.x@dev' || matrix.symfony-version == '6.0.x@dev'

      - name: Remove not compatible vendors
        run: composer remove --no-update --dev friendsofphp/php-cs-fixer
        if: matrix.symfony-version == '6.0.x@dev'

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v1

      - name: Run PHPUnit
        run: vendor/bin/simple-phpunit --coverage-clover=coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.php-version == '8.0' && matrix.symfony-version == '5.3.*'
